
jwt.secret-key: ${JWT_SECRET_KEY}

spring:
  profiles:
    active: prod

  datasource:
    platform: postgres
    url: jdbc:postgresql://balarama.db.elephantsql.com:5432/rodlxrkv
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql