version: 2.0

jobs:

  build:
    docker:
      - image: circleci/openjdk:11.0.6-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
      - run: chmod +x ./mvnw
      - run: ./mvnw -Dmaven.test.skip=true package
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: ./
          paths:
            - target/

  test:
    docker:
      - image: circleci/openjdk:11.0.6-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
      - attach_workspace:
          at: ./target
      - run: chmod +x ./mvnw
      - run: ./mvnw test
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/site/jacoco/index.html

  deploy:
    docker:
      - image: circleci/openjdk:11.0.6-jdk-stretch
    steps:
      - checkout
      - run: echo "deploy not configured"

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test