###
GET http://localhost:8080/api/v1/alarm
Content-Type: application/json
Authorization: Bearer JWT_BEARER_TOKEN

###

POST http://localhost:8080/api/v1/alarm
Content-Type: application/json
Authorization: Bearer JWT_BEARER_TOKEN

{
  "alarmFrequencyCostume": [],
  "alarmFrequencyType": [
    "FRIDAY",
    "THURSDAY",
    "WEDNESDAY",
    "TUESDAY"
  ],
  "alarmTurnOffType": "NORMAL",
  "isActive": true,
  "name": "",
  "ringType": "BIRDS",
  "snooze": "MIN_5",
  "time": {
    "hours": 14,
    "minutes": 51,
    "seconds": 0
  }
}

###

PUT http://localhost:8080/api/v1/alarm
Content-Type: application/json
Authorization: Bearer JWT_BEARER_TOKEN

{
  "id": "ID",
  "alarmFrequencyCostume": [],
  "alarmFrequencyType": [
    "FRIDAY",
    "THURSDAY",
    "WEDNESDAY",
    "TUESDAY"
  ],
  "alarmTurnOffType": "NORMAL",
  "isActive": true,
  "name": "",
  "ringType": "BIRDS",
  "snooze": "MIN_5",
  "time": {
    "hours": 14,
    "minutes": 51,
    "seconds": 0
  }
}

### Create alarm with minimal fields

PUT http://localhost:8080/api/v1/alarm
Content-Type: application/json
Authorization: Bearer JWT_BEARER_TOKEN

{
  "alarmFrequencyType" : [
    "MONDAY", "CUSTOM"
  ],
  "time" : {
    "hours": 17,
    "minutes": 51,
    "seconds": 45
  },
  "alarmFrequencyCostume" : [
    {
      "day" : "1",
      "month" : "1",
      "year" : "2000"
    },
    {
      "day" : "2",
      "month" : "2",
      "year" : "2000"
    }
  ]
}
