###
GET http://localhost:8080/api/v1/alarm
Content-Type: application/json
Authorization: Bearer JWT_BEARER_TOKEN

###

POST http://localhost:8080/api/v1/alarm
Content-Type: application/json
Authorization: Bearer JWT_BEARER_TOKEN

{
  "alarmFrequencyCostume": [],
  "alarmFrequencyType": [
    "FRIDAY",
    "THURSDAY",
    "WEDNESDAY",
    "TUESDAY"
  ],
  "alarmTurnOffType": "NORMAL",
  "isActive": true,
  "name": "",
  "ringType": "BIRDS",
  "snooze": "MIN_5",
  "time": {
    "hours": 14,
    "minutes": 51,
    "seconds": 0
  }
}

###

PUT http://localhost:8080/api/v1/alarm
Content-Type: application/json
Authorization: Bearer JWT_BEARER_TOKEN

{
  "id": "ID",
  "alarmFrequencyCostume": [],
  "alarmFrequencyType": [
    "FRIDAY",
    "THURSDAY",
    "WEDNESDAY",
    "TUESDAY"
  ],
  "alarmTurnOffType": "NORMAL",
  "isActive": true,
  "name": "",
  "ringType": "BIRDS",
  "snooze": "MIN_5",
  "time": {
    "hours": 14,
    "minutes": 51,
    "seconds": 0
  }
}

### Create alarm with minimal fields

PUT http://localhost:8080/api/v1/alarm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYwMjc3NTQ1OCwiaWF0IjoxNjAyNzczNjU4fQ.cpMCWNqQ_1yxWyNxM4FzzHpC_xebQO2YVqXN_0QSoxY

{
  "alarmFrequencyType" : [
    "MONDAY"
  ],
  "time" : {
    "hours": 17,
    "minutes": 51,
    "seconds": 45
  }
}
